# Generated by Django 2.1.7 on 2021-02-04 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('director_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('courses', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('roll_number', models.IntegerField()),
                ('course', models.CharField(max_length=10)),
                ('College', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='myDBApp.College')),
            ],
        ),
    ]
